version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

